default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fambam_development

test: &test
  <<: *default
  database: fambam_test

production:
  <<: *default
  database: fambam_production

